### ISSUE TITLE
Having some trouble in following the tutorial

### ISSUE THREAD

**Issue by Faustino-ai** [aNetdev/GoogleActions#1]
Hello Arun,
Thanks for the great tutorial. However I am having some issues on the exposing the url to the internet part, where google can access urls (fulfillment, auth and token). I know you mentioned that this is out of the scope of this tutorial but can you share some link for an example to do this? I find it quite difficult to comprehend the Nginx Proxy Manager part without a proper guide.

**Comment by anetdev** [comment]
sorry didn't notice your question until now. let me know if you are still looking for an answer,

**Comment by Faustino-ai** [comment]
Don't worry about it. I managed to figure out slightly how to do it. Thanks again for the great tutorial.
